apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smokeping.fullname" . }}
  labels:
    {{- include "smokeping.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "smokeping.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "smokeping.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "smokeping.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "smokeping.fullname" . }}-config
              mountPath: /config
            - name: {{ include "smokeping.fullname" . }}-site-conf
              mountPath: /config/site-confs
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: {{ include "smokeping.fullname" . }}-config
          configMap:
            name: {{ include "smokeping.fullname" . }}-config
        - name: {{ include "smokeping.fullname" . }}-site-conf
          configMap:
            name: {{ include "smokeping.fullname" . }}-site-conf
        - name: data
{{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
{{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.existingClaim }}
{{- else }}
            claimName: {{ include "smokeping.fullname" . }}
{{- end }}
{{- else if not .Values.persistence.enabled }}
          emptyDir: {}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
