apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-site-conf
data:
  {{ $root := . }}
  {{ range $path, $bytes := .Files.Glob "config/site-confs/*" }}
  {{ base $path }}: |+
    {{ $root.Files.Get $path | nindent 4 }}
  {{ end }}